url: http://migsalazar/sqlserver-course
baseurl: ""
site_title:  Curso de Sql Server

exclude:
  - _site
  - _drafts/

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouges

collections:
    content:
        output: true
        permalink: /:path/
        title: Prueba
